apiVersion: v1
kind: Service
metadata:
  namespace: traefik
  name: traefik-ingress-service
spec:
  selector:
    k8s-app: traefik-ingress-lb
  type: NodePort
  ports:
    - name: web
      port: 80
      nodePort: 30080
      protocol: TCP
    - name: admin
      port: 8080
      nodePort: 30880
      protocol: TCP