kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gobernetes-pvc
  namespace: go-ws
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 0.5Gi
