apiVersion: v1
data:
  alertmanager.yaml: Z2xvYmFsOiAKICByZXNvbHZlX3RpbWVvdXQ6IDVtCiAgc2xhY2tfYXBpX3VybDogJ2h0dHBzOi8vaG9va3Muc2xhY2suY29tL3NlcnZpY2VzL1QwUzRVR1VLMC9CRkJNNUtEM1AvVEtia1d6djJqVmYxb1lKaHZ6VFZiVXlHJwoKcm91dGU6IAogIHJlY2VpdmVyOiAnc2xhY2snCgpyZWNlaXZlcnM6IAotIG5hbWU6ICdzbGFjaycKICBzbGFja19jb25maWdzOgogIC0gY2hhbm5lbDogJyNrdWJlcm5ldGVzJwogICAgdGV4dDogTmV3IG9uZQoK
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
type: Opaque
