apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: traefik-web-ui
  namespace: traefik
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-dev
    certmanager.k8s.io/acme-challenge-type: dns01
    certmanager.k8s.io/acme-dns01-provider: route53
spec:
  rules:
    - host: raca-traefik.ballab.com
      http:
        paths:
          - backend:
              serviceName: traefik-web-ui
              servicePort: 80
  tls:
    - hosts:
        - raca-traefik.ballab.com
      secretName: raca-traefik-ballab-com-tls