---
apiVersion: v1
kind: Service
metadata:
  name: go-ws-lb
  namespace: go-ws
spec:
  selector:
    app: go-ws
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-ws-deployment
  namespace: go-ws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-ws
  template:
    metadata:
      labels:
        app: go-ws
    spec:
      containers:
      - name: go-ws
        image: aracki/go-web-server
        imagePullPolicy: Always
        ports:                                      
        - containerPort: 8080
          name: http
        volumeMounts:
          - mountPath: "/tmp/"
            name: gobernetes-pv
      volumes:
        - name: gobernetes-pv
          persistentVolumeClaim:
            claimName: gobernetes-pvc
---
